### PR TITLE
[CUBRIDQA-58] fix log folder make and category

### PR DESCRIPTION
**Pull request by supler**
@fanzaiqiang 

fix log folder make and category during testing

### CODE REVIEW

**Comment by fanzaiqiang** [comment]
@supler 

Please merge the patch.

**Comment by supler** [comment]
@fanzaiqiang 

I correct the path of server

**Comment by fanzaiqiang** [comment]
@supler 

Please merge the patch.

**Comment by fanzaiqiang** [comment]
@supler 

Please go ahead.

**Pull request merged**
