### PR TITLE
[CUBRIDQA-33] support shell and isolation test

### PR DESCRIPTION
**Pull request by fanzaiqiang**
In this pull request, we enhanced CTP to support both shell and isolation test.

How to execute test:
```
ctp.sh shell -c CTP/conf/shell.conf
ctp.sh isolation -c CTP/conf/isolation.conf
```
Both shell and isolation tests are designed to execute on multiple test nodes since they are slow on execution. The unique control node and one or more test nodes should all deploy CTP program.
And test cases should be checked out in each test nodes.  And you have to spend a little time on configuration. 
In each test node of shell test, you should set environmental variable ```init_path```, like ```export init_path=$HOME/CTP/shell/init_path```;  In each test node of isolation test, it requires like ```export CTP_HOME=$HOME/CTP```.  Actually, we expect only CTP_HOME is always used. Currently, all existing shell test cases are using ```$init_path``` .

### CODE REVIEW

**Comment by xkyu** [comment]
How can I test the shell and isolation test with a single node?
And, 
When can you eliminate the 'init_path' env var?

**Comment by fanzaiqiang** [comment]
@xkyu 
"How can I test the shell and isolation test with a single node?"
By current design, the only way to execute in single node is to config test node as local. That means even though controller and test nodes are installed together, they will communicate via ssh. The shortage of this way is that all active processes for controller are easy to be killed by clean scripts (written in CTP tools or test cases).
env.instance1.ssh.host=127.0.0.1
env.instance1.ssh.port=22
env.instance1.ssh.user=<user>
env.instance1.ssh.pwd=<pwd>

"When can you eliminate the 'init_path' env var?"
All test cases adopts ```init_path``` with hard codes.  That's why we keep the only var.

**Comment by xkyu** [comment]
@fanzaiqiang 
I think it is very bad design. Please re-design or improve it later.
and
Why don't you set the 'init_path' using 'CTP_HOME' implicitly if it is not set by user?

**Comment by fanzaiqiang** [comment]
@xkyu 
"I think it is very bad design. Please re-design or improve it later."
CTP is somewhat easy to support single test node on improving.  But there are more works on modifying test cases (Need more evaluation). We may enhance it in next milestone.  One alternative way is to create two OS users in one machine node. One is for controller, the other is for test.  Actually, for HA shell and HA repl tests, more nodes must be involved. So we hope users may accept more distributed deployment.

"Why don't you set the 'init_path' using 'CTP_HOME' implicitly if it is not set by user?"
For isolation test, CTP_HOME is already adopt as our expected. But for shell test, we thought that when user hope to execute some test case by standalone without the aid of CTP controller, ```$init_path``` must be set first because test cases use it in codes.  So we keep it as the unique environmental variable.  If you hope to improve to CTP_HOME, we may change it.

**Comment by xkyu** [comment]
I think the 'init_path' can be set using the 'CTP_HOME'. 
(=> for eg: init_path=$CTP_HOME/shell/init_path )
Please minimize the prepare steps.

**Comment by fanzaiqiang** [comment]
@xkyu 

Okay. It will be improved to:
- when execute shell test by CTP as controller:  user only need set ```CTP_HOME``` var in test node.
```init_path``` will be set internally.
- when execute single shell test case by manual, user need set ```$init_path``` var.

**Comment by fanzaiqiang** [comment]
Finished improving to use CTP_HOME for shell test.

**Comment by xkyu** [comment]
Thanks. Please remove the requirement of multi-nodes limitation later.

**Comment by fanzaiqiang** [comment]
@xkyu 

About removing the requirement of multi-nodes limitation,
a new issue has been created to trace it. Please refer to CUBRIDQA-59.

**Pull request merged**
