### PR TITLE
[CUBRIDQA-1194] Apply Java code-style for cubrid-testtools

### PR DESCRIPTION
**Pull request by hgryoo**
http://jira.cubrid.org/browse/CUBRIDQA-1194

- Apply indentation code style (google-java-format 1.7)
  - CQT
  - Java SP functions

Please refer to the following command to apply indentation only for changed files.
```
cd cubrid-testtools
git diff --name-only "*.java" | while IFS= read -r n; do indent $(realpath -s $n); done
```
Note that the real path of google-java-format-1.7... should be rewritten in code_style.sh

- Add Github action workflow to check code style on PR

- CTP/sql/src/name/fraser/neil/plaintext/diff_match_patch.java is not added because the code seems to be from an external project.

### CODE REVIEW

**Comment by hiclass** [comment]
CTP/conf/sql_by_cci.conf dosen't have in this branch.
even if i make sql_by_cci.conf, sql_by_cci is not working.

**Comment by hgryoo** [comment]
> CTP/conf/sql_by_cci.conf dosen't have in this branch. even if i make sql_by_cci.conf, sql_by_cci is not working.

There is no deleting changes in the PR. Also there exists sql_by_cci.conf in the develop branch. Please check your workspace.

To clean your workspace
```
git checkout CUBRIDQA-1194
git clean -df
git reset --hard HEAD
```

**Comment by hiclass** [comment]
cubrid-testcasese 
sql, cciby_sql: pass
shell: on checking

**Review by hiclass — APPROVED** [review]
SQL/MEDIUM/SQL_BY_CCI Passed
LGTM

**Review by ssihil — APPROVED** [review]

**Pull request merged**
